/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Rene' at '5/5/14 1:40 PM' with Gradle 2.0-20140425121723+0000
 *
 * @author Rene, @date 5/5/14 1:40 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
